# Generated by Django 3.0.2 on 2020-03-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escBackend', '0003_comment_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Edited',
        ),
        migrations.AddField(
            model_name='comment',
            name='Pass_Fail',
            field=models.IntegerField(default=-1),
        ),
    ]
