# Generated by Django 3.0.2 on 2020-03-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escBackend', '0004_auto_20200305_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='Finished',
            field=models.BooleanField(default=False),
        ),
    ]
